# Site settings
title: zdd's Blog
SEOTitle: zdd的秘密花园 | zdd's Blog
header-img: img/home-bg.jpg
email: leehua095@gmail.com
description: "我叫钟东东，欢迎来到我的秘密花园！"
keyword: "钟东东，众品鑫驫鱻靐龘，为了防止被盒取了一个名字"
url: "https://dongdongzzz.github.io" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
#weibo_username: huxpro
#zhihu_username: huxpro
#github_username: huxpro
#twitter_username: huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude:
  [
    "less",
    "node_modules",
    "Gruntfile.js",
    "package.json",
    "README.md",
    "README.zh.md",
  ]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Disqus settings
disqus_username: hux

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: "UA-49627206-1" # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "哈喽！我叫钟东东，欢迎你来探索我的秘密花园！ </br>[水源社区](https://shuiyuan.sjtu.edu.cn/u/%E4%B8%BA%E4%BA%86%E9%98%B2%E6%AD%A2%E8%A2%AB%E7%9B%92%E5%8F%96%E4%BA%86%E4%B8%80%E4%B8%AA%E5%90%8D%E5%AD%97/summary) </br> [知乎](https://www.zhihu.com/people/zhong-pin-xin-biao-xian-bing-ta) </br> [QQ](https://qm.qq.com/q/l48IATVvvq) </br> [小红书](https://www.xiaohongshu.com/user/profile/62c028a2000000001b025feb?xsec_token=YBWr7lh1Skz64E1roPM1V47OX6zHmfAnYYN0PoQ3CRY2k%3D&xsec_source=app_share&xhsshare=CopyLink&appuid=62c028a2000000001b025feb&apptime=1739368783&share_id=be4b7d4ec2fa4c46b83b4fa48c900d0d&share_channel=copy_link)"
sidebar-avatar: https://notes.sjtu.edu.cn/uploads/upload_644cdd9baeb6a8a97a4ce16613f2f532.gif # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: false # whether or not using Feature-Tags
featured-condition-size: 1 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false

# Friends
#friends:
#  [
#    { title: "乱序（Midare）", href: "http://mida.re/" },
#    { title: "Ebn Zhang", href: "https://ebnbin.dev/" },
#    { title: "Kun Qian", href: "http://kunq.me" },
#    { title: "Sherry Woo", href: "https://sherrywoo.me/" },
#    { title: "SmdCn", href: "http://blog.smdcn.net" },
#    { title: "JiyinYiyong", href: "http://tiye.me/" },
#    { title: "DHong Say", href: "http://dhong.co" },
#    { title: "尹峰以为", href: "http://ingf.github.io/" },
#  ]
